# custom-values.yaml for Prometheus

alertmanager:
  enabled: true
  config:
    global:
      smtp_smarthost: "localhost:25"
      smtp_from: "alertmanager@example.com"
    route:
      group_by: ["alertname"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: "email"
    receivers:
      - name: "email"
        email_configs:
          - to: "malouch.ilef@gmail.com"

server:
  retention: "10d" # Adjust the data retention period as needed
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "512Mi"

  service:
    annotations: {}
    labels: {}

  persistentVolume:
    enabled: true
    size: "20Gi" # Adjust the storage size as needed

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

pushgateway:
  enabled: true

# Additional scrape configurations can be added here
additionalScrapeConfigs: |
  - job_name: 'kubernetes-nodes'
    scrape_interval: 15s
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
