apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: zaineb644/myapp:3

---
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-service
# spec:
#   selector:
#     app: my-app
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#   type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
spec:
  ports:
    - nodePort: 30172
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: my-app
  type: NodePort
