apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: zaineb644/myapp:2

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

---
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-loadbalancer-service
# spec:
#   ports:
#     - nodePort: 30171
#       port: 80
#       protocol: TCP
#       targetPort: 80
#   selector:
#     app: my-app
#   type: NodePort
